export type Block = { h?: string; p?: string; ul?: string[] }
export type Article = { slug: string; title: string; excerpt: string; category: string; date: string; read: string; body: Block[] }

export const ARTICLES: Article[] = [
  {
    slug: 'pre-seed-pitch-investors-actually-read',
    title: 'How to prepare a pre-seed pitch investors actually read',
    excerpt: 'Most decks fail before slide three, not because the idea is weak but because the reader cannot find the point. Here is how to write one that gets a reply.',
    category: 'Investment', date: '2026-09-01', read: '5 min',
    body: [
      { p: 'Early-stage investors read hundreds of decks a month. Yours gets about ninety seconds before the reader decides whether to keep going. Most pre-seed pitches lose that decision on the first three slides, and almost never because the idea is bad. They lose it because the reader cannot find the point.' },
      { h: 'Lead with the problem, not the product' },
      { p: 'Open with the specific problem, who has it, and how they cope today. A reader who nods at slide one will forgive a lot later. A reader who is still asking "what is this?" on slide four will not. Save features for after the problem lands, and describe the product in one sentence a non-technical person could repeat.' },
      { h: 'Answer why now and why you' },
      { p: 'Every good idea has been possible for years. What changed: a regulation, a cost curve, a behaviour, a technology that just became cheap? Then explain why your team is the one to do it. Domain experience, an unfair distribution advantage, or a hard-won insight all count. Enthusiasm alone does not.' },
      { h: 'Be honest about the numbers you do not have' },
      { p: 'At pre-seed nobody expects revenue. They do expect you to know your market size from the bottom up, your rough unit economics, and the two or three assumptions the whole plan depends on. A clearly labelled assumption builds more trust than a confident number with no source.' },
      { h: 'Ask for something specific' },
      { p: 'State the round size, what it buys in plain terms (months of runway, the hires, the milestone), and what the next round looks like if it works. Vague asks get vague replies.' },
      { ul: ['Twelve slides or fewer, one idea per slide', 'Problem, solution, why now, why you, market, traction, business model, team, ask', 'A demo link or a two-minute video beats ten screenshots', 'Send as a PDF, never a link that expires', 'Follow up once, a week later, with one new fact'] },
      { p: 'If you are building something and want a candid read on your deck before you send it to anyone else, that is exactly what our investment desk is for.' },
    ],
  },
  {
    slug: 'six-sigma-for-growing-companies',
    title: 'Six Sigma for growing companies: where to actually start',
    excerpt: 'Six Sigma has a reputation for factories and Fortune 500 firms. The useful part applies to any company that has grown past the point where the founder can see everything.',
    category: 'Business', date: '2026-08-25', read: '6 min',
    body: [
      { p: 'Six Sigma sounds like something that belongs on a factory floor with a wall of certificates behind it. Strip away the belts and the jargon and what is left is a simple discipline: find where your work produces inconsistent results, measure it, fix the cause, and make sure it stays fixed. That applies to a forty-person software company as much as to a plant.' },
      { h: 'The five steps that matter' },
      { ul: ['Define: pick one process and state, in a sentence, what a defect looks like to the customer', 'Measure: get real numbers on how often it happens and what it costs', 'Analyse: find the root cause, not the most visible symptom', 'Improve: change the process, test the change, keep what works', 'Control: build the check into the routine so the fix survives the next hire'] },
      { p: 'That is DMAIC. Everything else in Six Sigma is tooling to do those five steps more rigorously.' },
      { h: 'Where growing companies see the fastest wins' },
      { p: 'Three places almost always pay back within a quarter. Customer onboarding, where every extra day before value is felt shows up in churn. Invoicing and collections, where small errors delay cash by weeks. And handoffs between teams, sales to delivery or support to engineering, where work falls through the gap and nobody owns it.' },
      { h: 'What to avoid' },
      { p: 'Do not try to measure everything. Pick one process, finish it, and let the result make the case for the next one. Do not run improvement as a side project for people who already have full jobs; give one person real time to own it. And do not confuse certification with results. A team that has fixed one costly process has learned more than a room full of green belts who have not.' },
      { p: 'We run process diagnostics for companies at exactly this stage. It starts with a week of looking, not a year of slides.' },
    ],
  },
  {
    slug: 'brand-identity-on-a-startup-budget',
    title: 'Brand identity on a startup budget: what to invest in first',
    excerpt: 'You cannot afford everything at once. Sequence matters more than spend, and getting the order wrong is what makes a rebrand expensive later.',
    category: 'Design', date: '2026-08-18', read: '5 min',
    body: [
      { p: 'Early companies usually get branding wrong in one of two ways. They spend nothing and end up with a logo from a generator, a deck in three different fonts and a website nobody trusts. Or they spend everything on a full identity before they know what the company is. The answer is neither. It is sequence.' },
      { h: 'The order that works' },
      { ul: ['One positioning sentence: who it is for, what it does, why it is different. Everything else is built on this', 'A name and a wordmark that survives at small sizes: favicon, app icon, email signature', 'One strong colour and one type pairing. Restraint here reads as confidence', 'Templates for the things you make every week: the pitch deck, the one-pager, social posts', 'The website, last, because by now it has something coherent to express'] },
      { h: 'The mistakes that cost the most later' },
      { p: 'Rebranding after you have traction is the expensive one. Customers, partners and press have learned a name and a look; changing it burns that. The second is inconsistency: a deck that looks nothing like the website that looks nothing like the product. Investors notice. They read it as a team that has not decided what it is.' },
      { h: 'When to bring in a studio' },
      { p: 'When the positioning sentence is settled and you are about to raise, launch or hire in a way that puts the brand in front of people who matter. A good studio will spend more time on that sentence than on the logo, and the logo will be better for it.' },
      { p: 'Our design team builds identities, decks and brand systems for companies at exactly this point, usually in weeks rather than months.' },
    ],
  },
  {
    slug: 'accounting-basics-founders-year-one',
    title: 'Accounting basics every founder should get right in year one',
    excerpt: 'Clean books are not a compliance chore. They are how you know whether the business is working, and they are the first thing an investor or buyer will look at.',
    category: 'Finance', date: '2026-08-11', read: '6 min',
    body: [
      { p: 'Most founders treat accounting as something to sort out later. Later is usually the week before a fundraise, when a diligence request lands and eighteen months of receipts have to be reconstructed. Doing a few things properly from the start costs almost nothing and saves that week entirely.' },
      { h: 'Separate the money on day one' },
      { p: 'A dedicated business account and card before the first transaction. Mixing personal and company spend is the single most common source of messy books, and untangling it later is slow and expensive.' },
      { h: 'Pick a method and stick to it' },
      { p: 'Cash accounting records money when it moves; accrual records it when it is earned or owed. Small service businesses often start on cash. Anyone with subscriptions, inventory or plans to raise should move to accrual early, because that is what investors and lenders expect to read.' },
      { h: 'Three reports, read monthly' },
      { ul: ['Profit and loss: are you making money, and where is it going', 'Cash flow: will you still be here in ninety days', 'Balance sheet: what you own, what you owe, and what the company is actually worth on paper'] },
      { p: 'If you only read one, read cash flow. Profitable companies run out of cash all the time.' },
      { h: 'Do not let deadlines find you' },
      { p: 'VAT, payroll taxes, corporate filings and annual accounts all have dates. Put them in a calendar the day you incorporate, and know which ones carry penalties. Operating across countries, as we do, multiplies this quickly.' },
      { h: 'Investor-ready from the start' },
      { p: 'Investor-ready books are simply books that are current, consistent and explainable. A monthly close, a clean chart of accounts and a folder of contracts you can find. That is the whole trick.' },
      { p: 'Our finance team runs monthly finance partnerships for founders who would rather build the company than the spreadsheet.' },
    ],
  },
  {
    slug: 'digital-marketing-when-ai-answers-the-search',
    title: 'Digital marketing when AI answers the search: what still works',
    excerpt: 'AI Overviews, ChatGPT and Perplexity now answer questions directly and the clicks are falling. Here is what has stopped working, what has not, and what to do about it.',
    category: 'Marketing', date: '2026-08-04', read: '6 min',
    body: [
      { p: 'For twenty years the deal was simple: rank on the first page, earn the click. That deal is changing. AI answers now sit above the results and often resolve the question without a visit. Traffic to informational pages is down across most industries. The instinct is to panic. The better response is to notice what the new engines reward.' },
      { h: 'Be the source the answer cites' },
      { p: 'AI engines still have to get their facts from somewhere, and they cite. Pages that win citations share traits: they answer the question directly in the first paragraph, they are structured with clear headings, they include original data or a specific point of view, and they make it obvious who wrote them and why they are credible. Generic content written to fill a keyword is exactly what gets summarised away.' },
      { h: 'Own the channels nobody can intermediate' },
      { p: 'An email list, a community, a newsletter people actually open. These were always valuable. Now they are the part of your marketing no search engine can sit in front of.' },
      { h: 'Paid still works, but intent has moved' },
      { p: 'Fewer top-of-funnel searches reach a website, so paid budgets should follow high-intent queries and retargeting rather than broad awareness terms. Cost per click on commercial terms is rising for exactly this reason. Landing pages have to earn the visit faster than before.' },
      { h: 'Measure what actually changed' },
      { p: 'Organic clicks are a shrinking proxy. Track branded search volume, direct traffic, mentions inside AI answers, and assisted conversions. A brand that is cited without being clicked is still winning, and your dashboard should show that.' },
      { ul: ['Rewrite your top twenty pages to answer in the first paragraph', 'Add real data, examples and named authors', 'Build the email list you should have started last year', 'Move paid spend toward intent and retargeting', 'Add AI-answer visibility to the monthly report'] },
      { p: 'This is the work our marketing team does every month for clients: search that still pays, and the channels that no algorithm can take away.' },
    ],
  },
  {
    slug: 'how-to-choose-a-software-development-partner',
    title: 'How to choose a software development partner (and not regret it)',
    excerpt: 'Most bad outsourcing stories start with the wrong first question. Here is how to evaluate a partner before the contract, and what to insist on inside it.',
    category: 'Technology', date: '2026-07-28', read: '5 min',
    body: [
      { p: 'Choosing a development partner is one of the more expensive decisions a growing company makes, and one of the least well made. The usual approach, compare day rates and pick a stack, optimises for the wrong things. Here is a better order.' },
      { h: 'Start with the problem, not the technology' },
      { p: 'A partner who leads with the framework they want to use has told you something. The right first conversation is about your users, your constraints and what the software has to do in a year, not this quarter. Technology choices should fall out of that, and a good partner will explain why.' },
      { h: 'Listen for how they say no' },
      { p: 'Any team will agree to build what you describe. The valuable ones push back: this feature is not worth its complexity, this timeline is fiction, this integration will hurt later. If you never hear a "no" during the sales process, you will hear a lot of them once the invoices start.' },
      { h: 'Insist on a small first engagement' },
      { p: 'A two to four week discovery or a bounded first release tells you more than any proposal. You see how they communicate, how they estimate, and whether the code is something your future team could inherit.' },
      { h: 'Ownership, documentation, handover' },
      { p: 'You should own the code, the repositories, the cloud accounts and the domain from day one. Documentation should be part of the definition of done, not a line item at the end. And ask, plainly, what happens if you want to take the work in-house or move it elsewhere. The answer tells you whether you are buying software or renting a dependency.' },
      { ul: ['Who owns the code and the accounts?', 'Show me a project you handed over and what happened next', 'What would you cut from this scope, and why?', 'How do you handle a change halfway through?', 'What does maintenance cost after launch?'] },
      { p: 'We build websites, platforms and software this way because we also own companies, and we know what it is like to inherit someone else\u2019s decisions.' },
    ],
  },
]

export const findArticle = (slug: string) => ARTICLES.find((a) => a.slug === slug)
export const fmtDate = (d: string) => new Date(d + 'T00:00:00').toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
